services:
  api-dev:
    build: .
    container_name: flask_api_dev
    restart: on-failure
    ports:
      - "5001:5000"
    networks:
      - dev-network
    depends_on:
      - db-dev

  db-dev:
    image: mysql:8.0.40-debian
    container_name: mysql_db_dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=str0ng_p@ssw0rd
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=db4dev$
      - MYSQL_DATABASE=flask_db_dev
    volumes:
      - flask-db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - dev-network
volumes:
  flask-db-data:


networks:
  dev-network:
